apiVersion: apps/v1
kind: Deployment
metadata:
  name: els-ci-test
  namespace: { { .Values.namespace } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: els-ci-test
  template:
    metadata:
      labels:
        app: els-ci-test
    spec:
      containers:
        - name: els-ci-test
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: { { .Values.service.port } }
          readinessProbe:
            httpGet:
              path: /health
              port: { { .Values.service.port } }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: { { .Values.service.port } }
            initialDelaySeconds: 10
            periodSeconds: 10
